import re
from strings.boyer_moore import search as search_bm
from strings.boyer_moore import search2 as search_za
from strings.knuth_morris_pratt import search as search_kmp

ps = '''
“I’ve been waiting 40 years for someone like you.” Those were the first words Daniel Ellsberg spoke to me when we met last year. Dan and I felt an immediate kinship; we both knew what it meant to risk so much — and to be irrevocably changed — by revealing secret truths.
One of the challenges of being a whistleblower is living with the knowledge that people continue to sit, just as you did, at those desks, in that unit, throughout the agency, who see what you saw and comply in silence, without resistance or complaint. They learn to live not just with untruths but with unnecessary untruths, dangerous untruths, corrosive untruths. It is a double tragedy: What begins as a survival strategy ends with the compromise of the human being it sought to preserve and the diminishing of the democracy meant to justify the sacrifice.
But unlike Dan Ellsberg, I didn’t have to wait 40 years to witness other citizens breaking that silence with documents. Ellsberg gave the Pentagon Papers to the New York Times and other newspapers in 1971; Chelsea Manning provided the Iraq and Afghan War logs and the Cablegate materials to WikiLeaks in 2010. I came forward in 2013. Now here we are in 2016, and another person of courage and conscience has made available the set of extraordinary documents that are published in The Assassination Complex, the new book out today by Jeremy Scahill and the staff of The Intercept. (The documents were originally published last October 15 in The Drone Papers.)
We are witnessing a compression of the working period in which bad policy shelters in the shadows, the time frame in which unconstitutional activities can continue before they are exposed by acts of conscience. And this temporal compression has a significance beyond the immediate headlines; it permits the people of this country to learn about critical government actions, not as part of the historical record but in a way that allows direct action through voting — in other words, in a way that empowers an informed citizenry to defend the democracy that “state secrets” are nominally intended to support. When I see individuals who are able to bring information forward, it gives me hope that we won’t always be required to curtail the illegal activities of our government as if it were a constant task, to uproot official lawbreaking as routinely as we mow the grass. (Interestingly enough, that is how some have begun to describe remote killing operations, as “cutting the grass.”)
A single act of whistleblowing doesn’t change the reality that there are significant portions of the government that operate below the waterline, beneath the visibility of the public. Those secret activities will continue, despite reforms. But those who perform these actions now have to live with the fear that if they engage in activities contrary to the spirit of society — if even a single citizen is catalyzed to halt the machinery of that injustice — they might still be held to account. The thread by which good governance hangs is this equality before the law, for the only fear of the man who turns the gears is that he may find himself upon them.
Hope lies beyond, when we move from extraordinary acts of revelation to a collective culture of accountability within the intelligence community. Here we will have taken a meaningful step toward solving a problem that has existed for as long as our government.
Former Director of the Central Intelligence Agency Gen. David Petraeus.
David Hume Kennerly/Getty Images
Not all leaks are alike, nor are their makers. Gen. David Petraeus, for instance, provided his illicit lover and favorable biographer information so secret it defied classification, including the names of covert operatives and the president’s private thoughts on matters of strategic concern. Petraeus was not charged with a felony, as the Justice Department had initially recommended, but was instead permitted to plead guilty to a misdemeanor. Had an enlisted soldier of modest rank pulled out a stack of highly classified notebooks and handed them to his girlfriend to secure so much as a smile, he’d be looking at many decades in prison, not a pile of character references from a Who’s Who of the Deep State.
There are authorized leaks and also permitted disclosures. It is rare for senior administration officials to explicitly ask a subordinate to leak a CIA officer’s name to retaliate against her husband, as appears to have been the case with Valerie Plame. It is equally rare for a month to go by in which some senior official does not disclose some protected information that is beneficial to the political efforts of the parties but clearly “damaging to national security” under the definitions of our law.
This dynamic can be seen quite clearly in the al Qaeda “conference call of doom” story, in which intelligence officials, likely seeking to inflate the threat of terrorism and deflect criticism of mass surveillance, revealed to a neoconservative website extraordinarily detailed accounts of specific communications they had intercepted, including locations of the participating parties and the precise contents of the discussions. If the officials’ claims were to be believed, they irrevocably burned an extraordinary means of learning the precise plans and intentions of terrorist leadership for the sake of a short-lived political advantage in a news cycle. Not a single person seems to have been so much as disciplined as a result of the story that cost us the ability to listen to the alleged al Qaeda hotline.
President Barack Obama talks with Vice President Joe Biden in the Oval Office, April 15, 2015.
Photo: The White House
If harmfulness and authorization make no difference, what explains the distinction between the permissible and the impermissible disclosure?
The answer is control. A leak is acceptable if it’s not seen as a threat, as a challenge to the prerogatives of the institution. But if all of the disparate components of the institution — not just its head but its hands and feet, every part of its body — must be assumed to have the same power to discuss matters of concern, that is an existential threat to the modern political monopoly of information control, particularly if we’re talking about disclosures of serious wrongdoing, fraudulent activity, unlawful activities. If you can’t guarantee that you alone can exploit the flow of controlled information, then the aggregation of all the world’s unmentionables — including your own — begins to look more like a liability than an asset.
Daniel Ellsberg, who leaked the Pentagon Papers detailing U.S. policy in the Vietnam War, Oct. 10, 1976.
Photo: Susan Wood/Getty Images
Truly unauthorized disclosures are necessarily an act of resistance — that is, if they’re not done simply for press consumption, to fluff up the public appearance or reputation of an institution. However, that doesn’t mean they all come from the lowest working level. Sometimes the individuals who step forward happen to be near the pinnacle of power. Ellsberg was in the top tier; he was briefing the secretary of defense. You can’t get much higher, unless you are the secretary of defense, and the incentives simply aren’t there for such a high-ranking official to be involved in public interest disclosures because that person already wields the influence to change the policy directly.
At the other end of the spectrum is Manning, a junior enlisted soldier, who was much nearer to the bottom of the hierarchy. I was midway in the professional career path. I sat down at the table with the chief information officer of the CIA, and I was briefing him and his chief technology officer when they were publicly making statements like “We try to collect everything and hang on to it forever,” and everybody still thought that was a cute business slogan. Meanwhile I was designing the systems they would use to do precisely that. I wasn’t briefing the policy side, the secretary of defense, but I was briefing the operations side, the National Security Agency’s director of technology. Official wrongdoing can catalyze all levels of insiders to reveal information, even at great risk to themselves, so long as they can be convinced that it is necessary to do so.
Reaching those individuals, helping them realize that their first allegiance as a public servant is to the public rather than to the government, is the challenge. That’s a significant shift in cultural thinking for a government worker today.
I’ve argued that whistleblowers are elected by circumstance. It’s not a virtue of who you are or your background. It’s a question of what you are exposed to, what you witness. At that point the question becomes Do you honestly believe that you have the capability to remediate the problem, to influence policy? I would not encourage individuals to reveal information, even about wrongdoing, if they do not believe they can be effective in doing so, because the right moment can be as rare as the will to act.
This is simply a pragmatic, strategic consideration. Whistleblowers are outliers of probability, and if they are to be effective as a political force, it’s critical that they maximize the amount of public good produced from scarce seed. When I was making my decision, I came to understand how one strategic consideration, such as waiting until the month before a domestic election, could become overwhelmed by another, such as the moral imperative to provide an opportunity to arrest a global trend that had already gone too far. I was focused on what I saw and on my sense of overwhelming disenfranchisement that the government, in which I had believed for my entire life, was engaged in such an extraordinary act of deception.
Change has to flow from the bottom to the top.
At the heart of this evolution is that whistleblowing is a radicalizing event — and by “radical” I don’t mean “extreme”; I mean it in the traditional sense of radix, the root of the issue. At some point you recognize that you can’t just move a few letters around on a page and hope for the best. You can’t simply report this problem to your supervisor, as I tried to do, because inevitably supervisors get nervous. They think about the structural risk to their career. They’re concerned about rocking the boat and “getting a reputation.” The incentives aren’t there to produce meaningful reform. Fundamentally, in an open society, change has to flow from the bottom to the top.
As someone who works in the intelligence community, you’ve given up a lot to do this work. You’ve happily committed yourself to tyrannical restrictions. You voluntarily undergo polygraphs; you tell the government everything about your life. You waive a lot of rights because you believe the fundamental goodness of your mission justifies the sacrifice of even the sacred. It’s a just cause.
And when you’re confronted with evidence — not in an edge case, not in a peculiarity, but as a core consequence of the program — that the government is subverting the Constitution and violating the ideals you so fervently believe in, you have to make a decision. When you see that the program or policy is inconsistent with the oaths and obligations that you’ve sworn to your society and yourself, then that oath and that obligation cannot be reconciled with the program. To which do you owe a greater loyalty?
The U.S. Capitol is reflected in a puddle next to the Capitol Reflecting Pool in Washington, D.C., Oct. 15, 2013.
Photo: Andrew Harrer/Bloomberg/Getty Images
One of the extraordinary things about the revelations of the past several years, and their accelerating pace, is that they have occurred in the context of the United States as the “uncontested hyperpower.” We now have the largest unchallenged military machine in the history of the world, and it’s backed by a political system that is increasingly willing to authorize any use of force in response to practically any justification. In today’s context that justification is terrorism, but not necessarily because our leaders are particularly concerned about terrorism in itself or because they think it’s an existential threat to society. They recognize that even if we had a 9/11 attack every year, we would still be losing more people to car accidents and heart disease, and we don’t see the same expenditure of resources to respond to those more significant threats.
What it really comes down to is the political reality that we have a political class that feels it must inoculate itself against allegations of weakness. Our politicians are more fearful of the politics of terrorism — of the charge that they do not take terrorism seriously — than they are of the crime itself.
As a result we have arrived at this unmatched capability, unrestrained by policy. We have become reliant upon what was intended to be the limitation of last resort: the courts. Judges, realizing that their decisions are suddenly charged with much greater political importance and impact than was originally intended, have gone to great lengths in the post-9/11 period to avoid reviewing the laws or the operations of the executive in the national security context and setting restrictive precedents that, even if entirely proper, would impose limits on government for decades or more. That means the most powerful institution that humanity has ever witnessed has also become the least restrained. Yet that same institution was never designed to operate in such a manner, having instead been explicitly founded on the principle of checks and balances. Our founding impulse was to say, “Though we are mighty, we are voluntarily restrained.”
President Barack Obama walks with U.S. Secret Service agents to Air Force One at Los Angeles International Airport in Los Angeles, Calif., May 8, 2014.
Photo: The White House
When you first go on duty at CIA headquarters, you raise your hand and swear an oath — not to government, not to the agency, not to secrecy. You swear an oath to the Constitution. So there’s this friction, this emerging contest between the obligations and values that the government asks you to uphold, and the actual activities that you’re asked to participate in.
These disclosures about the Obama administration’s killing program reveal that there’s a part of the American character that is deeply concerned with the unrestrained, unchecked exercise of power. And there is no greater or clearer manifestation of unchecked power than assuming for oneself the authority to execute an individual outside of a battlefield context and without the involvement of any sort of judicial process.
Traditionally, in the context of military affairs, we’ve always understood that lethal force in battle could not be subjected to ex ante judicial constraints. When armies are shooting at each other, there’s no room for a judge on that battlefield. But now the government has decided — without the public’s participation, without our knowledge and consent — that the battlefield is everywhere. Individuals who don’t represent an imminent threat in any meaningful sense of those words are redefined, through the subversion of language, to meet that definition.
Inevitably that conceptual subversion finds its way home, along with the technology that enables officials to promote comfortable illusions about surgical killing and nonintrusive surveillance. Take, for instance, the Holy Grail of drone persistence, a capability that the United States has been pursuing forever. The goal is to deploy solar-powered drones that can loiter in the air for weeks without coming down. Once you can do that, and you put any typical signals collection device on the bottom of it to monitor, unblinkingly, the emanations of, for example, the different network addresses of every laptop, smartphone, and iPod, you know not just where a particular device is in what city, but you know what apartment each device lives in, where it goes at any particular time, and by what route. Once you know the devices, you know their owners. When you start doing this over several cities, you’re tracking the movements not just of individuals but of whole populations.
Unrestrained power may be many things, but it’s not American.
By preying on the modern necessity to stay connected, governments can reduce our dignity to something like that of tagged animals, the primary difference being that we paid for the tags and they’re in our pockets. It sounds like fantasist paranoia, but on the technical level it’s so trivial to implement that I cannot imagine a future in which it won’t be attempted. It will be limited to the war zones at first, in accordance with our customs, but surveillance technology has a tendency to follow us home.
Here we see the double edge of our uniquely American brand of nationalism. We are raised to be exceptionalists, to think we are the better nation with the manifest destiny to rule. The danger is that some people will actually believe this claim, and some of those will expect the manifestation of our national identity, that is, our government, to comport itself accordingly.
Unrestrained power may be many things, but it’s not American. It is in this sense that the act of whistleblowing increasingly has become an act of political resistance. The whistleblower raises the alarm and lifts the lamp, inheriting the legacy of a line of Americans that begins with Paul Revere.
The individuals who make these disclosures feel so strongly about what they have seen that they’re willing to risk their lives and their freedom. They know that we, the people, are ultimately the strongest and most reliable check on the power of government. The insiders at the highest levels of government have extraordinary capability, extraordinary resources, tremendous access to influence, and a monopoly on violence, but in the final calculus there is but one figure that matters: the individual citizen.
And there are more of us than there are of them.
From by Jeremy Scahill and the staff of The Intercept, with a foreword by Edward Snowden and afterword by Glenn Greenwald, published by Simon & Schuster.
'''.split()
t = ''.join(ps)  # spaces make search too easy
for p in ps:
    control = [x.start() for x in re.finditer(re.escape(p), t)]  # all non-overlapping matches
    bm = list(search_bm(t, p))
    za = list(search_za(t, p))
    kmp = list(search_kmp(t, p))
    assert control == bm == za == kmp
